### ISSUE TITLE
NPC Can't Join

### ISSUE THREAD

**Issue by SpirusAnunnaki** [sailex428/AI-NPC-Launcher#8]
It seems the NPC is ignoring the default port (25565) or whatever port I set it to through /setconfig and apparently uses a random port each time I attempt to connect them.

**Comment by sailex428** [comment]
Which version of the mod do you use? If you dont have the latest version installed, i would recommend to install that and try again. (From v1.0.5 its only serverside).

**Comment by SpirusAnunnaki** [comment]
I am using the latest version (1.0.5)

**Comment by sailex428** [comment]
Usually, the NPC client automatically connects to localhost:25565. Changing the port via /setconfig is only necessary if your mc server is running on a different port. In general, I would recommend reading the description of the mod if you have not done so. Could you share the server logs? They might provide more insight into what’s going wrong.

**Comment by sailex428** [comment]
I'll close this issue now cause of inactivity!
